# IMPORT LIBRARY

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# IMPORTING DATASET

In [2]:
Data = pd.read_excel('hourlydataten.xlsx')
Data.head()

,time,temperature_2m (°C),relative_humidity_2m (%),dew_point_2m (°C),apparent_temperature (°C),precipitation (mm),rain (mm),snowfall (cm),pressure_msl (hPa),surface_pressure (hPa),...,wind_direction_100m (°),wind_gusts_10m (km/h),soil_temperature_0_to_7cm (°C),soil_temperature_7_to_28cm (°C),soil_temperature_28_to_100cm (°C),soil_temperature_100_to_255cm (°C),soil_moisture_0_to_7cm (m³/m³),soil_moisture_7_to_28cm (m³/m³),soil_moisture_28_to_100cm (m³/m³),soil_moisture_100_to_255cm (m³/m³)
0,2014-01-01 05:00:00,14.9,63,8.0,14.1,0.0,0.0,0.0,1022.2,945.8,...,259,13.7,12.6,10.8,13.8,18.4,0.290,0.198,0.248,0.364
1,2014-01-01 06:00:00,16.1,60,8.4,15.1,0.0,0.0,0.0,1022.2,946.1,...,240,16.6,14.6,11.1,13.7,18.4,0.288,0.198,0.248,0.364
2,2014-01-01 07:00:00,16.0,64,9.2,15.0,0.0,0.0,0.0,1021.1,945.0,...,238,20.2,15.6,11.4,13.7,18.4,0.286,0.198,0.248,0.364
3,2014-01-01 08:00:00,16.0,64,9.2,14.9,0.0,0.0,0.0,1020.4,944.4,...,235,21.2,15.9,11.7,13.7,18.4,0.285,0.198,0.248,0.364
4,2014-01-01 09:00:00,16.1,65,9.4,14.8,0.0,0.0,0.0,1019.6,943.7,...,239,19.8,16.0,12.0,13.7,18.4,0.283,0.199,0.248,0.364

In [5]:
Data['Date'] = dataframe['time'].dt.date
wdata = dataframe.groupby('Date').mean()
wdata = wdata.drop(columns=['time'])
wdata

NameError: name 'dataframe' is not defined